#!/bin/bash
#
# Sample LITP multi-blade deployment (SAN version)
#
# Usage:
#   ST_Deployment_15.sh <CLUSTER_SPEC_FILE>
#

#if [ "$#" -lt 1 ]; then
#    echo -e "Usage:\n  $0 <CLUSTER_SPEC_FILE>" >&2
#    exit 1
#fi

#cluster_file="$1"
#source "$cluster_file"

set -x

# MS ONLY STUFF, PHIL.
litp update -p /ms -o hostname="ieatlms3849-1"
litp create -p /ms/configs/dns_client -t dns-client -o search=athtem.eei.ericsson.se
litp create -p /ms/configs/dns_client/nameservers/nameserver_A -t nameserver -o ipaddress=159.107.173.3 position=1
litp create -p /ms/configs/dns_client/nameservers/nameserver_B -t nameserver -o ipaddress=159.107.173.12 position=2


# SYSCTRL PARAMS FOR MS
litp create -p /ms/configs/sysctl -t sysparam-node-config
litp create -p /ms/configs/sysctl/params/core_pattern -t sysparam -o key=kernel.core_pattern value="/ericsson/enm/dumps/core.%e.pid%p.usr%u.sig%s.tim%t1"

# SETUP ALIAS' ON MS
litp create -p /ms/configs/alias_configuration -t alias-node-config
litp create -p /ms/configs/alias_configuration/aliases/httpd_alias -t alias -o alias_names="haproxy,ieatENM5183-1.athtem.eei.ericsson.se" address="10.151.9.137"



litp create -p /infrastructure/networking/networks/services_network -t network -o litp_management="false" name="services" subnet"10.151.9.128/26"
litp create -p /infrastructure/networking/networks/storage_network -t network -o  litp_management="false" name="storage" subnet="10.140.2.0/24"
litp create -p /infrastructure/networking/networks/backup_network -t network -o litp_management="false" name="backup" subnet="10.151.24.0/23"
litp create -p /infrastructure/networking/networks/internal_network -t network -o litp_management="true" name="internal" subnet="10.247.244.0/22"




litp create -p /infrastructure/storage/nfs_mounts/nfsm-brsadm_home -t nfs-mount -o export_path="/vx/ENM183-brsadm_home" mount_options="soft" mount_point="/opt/ericsson/storage/user/nas/brsadm" network_name="storage" provider="vs_enm_2"
litp create -p /infrastructure/storage/nfs_mounts/nfsm-storobs_home -t nfs-mount -o export_path="/vx/ENM183-storobs_home" mount_options="soft" mount_point="/opt/ericsson/storage/user/nas/storobs" network_name="storage" provider="vs_enm_1"
litp create -p /infrastructure/storage/nfs_mounts/nfsm-data -t nfs-mount -o export_path="/vx/ENM183-data" mount_options="soft" mount_point="/ericsson/tor/data" network_name="storage" provider="vs_enm_1"
litp create -p /infrastructure/storage/nfs_mounts/nfsm-ddc_data -t nfs-mount -o export_path="/vx/ENM183-ddc_data" mount_options="soft" mount_point="/var/ericsson/ddc_data" network_name="storage" provider="vs_enm_2"
litp create -p /infrastructure/storage/nfs_mounts/nfsm-hcdumps -t nfs-mount -o export_path="/vx/ENM183-hcdumps" mount_options="soft" mount_point="/ericsson/enm/dumps" network_name="storage" provider="vs_enm_1"
litp create -p /infrastructure/storage/nfs_mounts/nfsm-mdt -t nfs-mount -o export_path="/vx/ENM183-mdt" mount_options="soft" mount_point="/etc/opt/ericsson/ERICmodeldeployment" network_name="storage" provider="vs_enm_1"
litp create -p /infrastructure/storage/nfs_mounts/nfsm-alex -t nfs-mount -o export_path="/vx/ENM183-alex" mount_options="soft" mount_point="/ericsson/enm/alex" network_name="storage" provider="vs_enm_1"

litp create -p /software/items/common_repo -t yum-repository -o ms_url_path="/ENM_common/" name="common_repo"
litp create -p /software/items/ms_repo -t yum-repository -o ms_url_path="/ENM_ms/" name="ms_repo"
litp create -p /software/items/model_repo -t yum-repository -o ms_url_path="/ENM_models/" name="model_repo"
litp create -p /software/items/ntp_service -t ntp-service
litp create -p /software/items/ntp_service/servers/ntp_server-1 -t ntp-server -o server="159.107.173.3"
litp create -p /software/items/ntp_service/servers/ntp_server-2 -t ntp-server -o server="10.140.2.9"
litp create -p /software/items/ddc_package -t package -o name="ERICddc_CXP9030294"
litp create -p /software/items/rsyslog8 -t package -o epoch=0 name="EXTRlitprsyslogelasticsearch_CXP9032173" replaces="rsyslog7"
litp create -p /software/items/enm_configuration -t package -o name="ERICenmconfiguration_CXP9031455"
litp create -p /software/items/config_manager -t config-manager -o global_properties_path="/ericsson/tor/data" group="root" mode="0644" owner="root"
litp create -p /software/items/config_manager/global_properties/internal_subnet -t config-manager-property -o key="internal_subnet" value="10.247.244.0/22"

litp create -p /software/items/config_manager/global_properties/property_internal_bind_nic -t config-manager-property -o key="internal_bind_nic" value="eth1"

litp create -p /software/items/config_manager/global_properties/property_jgroups_bind_nic -t config-manager-property -o key="jgroups_bind_nic" value="eth2"

litp create -p /software/items/config_manager/global_properties/property_public_bind_nic -t config-manager-property -o key="public_bind_nic" value="eth3"

litp create -p /software/items/config_manager/global_properties/property_webhost -t config-manager-property -o key="web_host_default" value="ieatENM5183-1.athtem.eei.ericsson.se"

litp create -p /software/items/config_manager/global_properties/property_web_host_ossMonitoring -t config-manager-property -o key="web_host_ossMonitoringHost" value="10.151.9.136"
litp create -p /software/items/config_manager/global_properties/property_web_host_eniqEventsHost -t config-manager-property -o key="web_host_eniqEventsHost" value="NOT_USED"
litp create -p /software/items/config_manager/global_properties/property_web_host_eniqStatsHost -t config-manager-property -o key="web_host_eniqStatsHost" value="NOT_USED"
litp create -p /software/items/config_manager/global_properties/property_web_host_eniqManagement -t config-manager-property -o key="web_host_eniqManagement" value="NOT_USED"
litp create -p /software/items/config_manager/global_properties/property_web_host_eniqBusinessHost -t config-manager-property -o key="web_host_eniqBusinessHost" value="NOT_USED"
litp create -p /software/items/config_manager/global_properties/property_web_host_alexHost -t config-manager-property -o key="web_host_alexHost" value="NOT_USED"
litp create -p /software/items/config_manager/global_properties/property_web_protocols_default -t config-manager-property -o key="web_protocols_default" value="https"
litp create -p /software/items/config_manager/global_properties/property_web_protocols_secure -t config-manager-property -o key="web_protocols_secure" value="https"
litp create -p /software/items/config_manager/global_properties/property_web_protocols_unsecure -t config-manager-property -o key="web_protocols_unsecure" value="http"
litp create -p /software/items/config_manager/global_properties/property_web_ports_default -t config-manager-property -o key="web_ports_default" value="443"
litp create -p /software/items/config_manager/global_properties/property_web_ports_unsecurePort -t config-manager-property -o key="web_ports_unsecurePort" value="80"
litp create -p /software/items/config_manager/global_properties/property_web_ports_securePort -t config-manager-property -o key="web_ports_securePort" value="443"
litp create -p /software/items/config_manager/global_properties/property_web_ports_appServer -t config-manager-property -o key="web_ports_appServer" value="8080"
litp create -p /software/items/config_manager/global_properties/property_web_ports_ossMonitoring -t config-manager-property -o key="web_ports_ossMonitoring" value="57004"
litp create -p /software/items/config_manager/global_properties/property_web_ports_eniqEventsPort -t config-manager-property -o key="web_ports_eniqEventsPort" value="18080"
litp create -p /software/items/config_manager/global_properties/property_ui_pres_serv -t config-manager-property -o key="UI_PRES_SERVER" value="ieatENM5183-1.athtem.eei.ericsson.se"
litp create -p /software/items/config_manager/global_properties/property_ha_proxy_sb -t config-manager-property -o key="haproxysb" value="10.151.9.171"
litp create -p /software/items/config_manager/global_properties/property_modcluster_listenport -t config-manager-property -o key="modcluster_listenport" value="8666"
litp create -p /software/items/config_manager/global_properties/property_jbossModulesPath -t config-manager-property -o key="jbossModulesPath" value="/opt/ericsson/jboss/modules"
litp create -p /software/items/config_manager/global_properties/property_sso_cookie_domain -t config-manager-property -o key="SSO_COOKIE_DOMAIN" value=".ericsson.se"
litp create -p /software/items/config_manager/global_properties/property_com_inf_ldap_port -t config-manager-property -o key="COM_INF_LDAP_PORT" value="1636"
litp create -p /software/items/config_manager/global_properties/property_com_inf_ldap_root_suffix -t config-manager-property -o key="COM_INF_LDAP_ROOT_SUFFIX" value="dc=ieatlms3849,dc=com"
litp create -p /software/items/config_manager/global_properties/property_com_inf_ldap_amin_cn -t config-manager-property -o key="COM_INF_LDAP_ADMIN_CN" value="uid=ssouser,ou=people,dc=ieatlms3849,dc=com"
litp create -p /software/items/config_manager/global_properties/property_ldap_amin_cn -t config-manager-property -o key="LDAP_ADMIN_CN" value="cn=directory manager"
litp create -p /software/items/config_manager/global_properties/property_com_inf_ldap_amin_access -t config-manager-property -o key="COM_INF_LDAP_ADMIN_ACCESS" value="U2FsdGVkX19frAkqzSIIsIymCS8d7pQO4d/2oU2lP1o="
litp create -p /software/items/config_manager/global_properties/property_ldap_amin_password -t config-manager-property -o key="LDAP_ADMIN_PASSWORD" value="U2FsdGVkX1922+mDrJRUUiHZ2l1FAJ0ytQsMYllbc1c="
litp create -p /software/items/config_manager/global_properties/property_openidm_admin_password -t config-manager-property -o key="openidm_admin_password" value="U2FsdGVkX19ICg/dSgvQgBLcPVxYg0MnGwslYy4HU6c="
litp create -p /software/items/config_manager/global_properties/property_idm_mysql_admin_password -t config-manager-property -o key="idm_mysql_admin_password" value="U2FsdGVkX1+nAEUrdumDpDt5C/170yuzN5rVMo8TdRI="
litp create -p /software/items/config_manager/global_properties/property_postgresql01_admin_password -t config-manager-property -o key="postgresql01_admin_password" value="U2FsdGVkX19vCqEbMlV7eM7792ggp2UXyS2x4H4KJro="
litp create -p /software/items/config_manager/global_properties/property_default_security_admin_password -t config-manager-property -o key="default_security_admin_password" value="U2FsdGVkX18ORFDybyxVCmgekdmv++cJ/JKGxvESKHQ="
litp create -p /software/items/config_manager/global_properties/property_pmicNfsShare -t config-manager-property -o key="pmicNfsShare" value="/ericsson/pmic1/"
litp create -p /software/items/config_manager/global_properties/property_pmicNfsShare2 -t config-manager-property -o key="pmicNfsShare2" value="/ericsson/pmic2/"
litp create -p /software/items/config_manager/global_properties/property_medrouter1 -t config-manager-property -o key="medrouter1" value="10.247.246.13"
litp create -p /software/items/config_manager/global_properties/property_medrouter2 -t config-manager-property -o key="medrouter2" value="10.247.246.14"
litp create -p /software/items/config_manager/global_properties/property_mscm1 -t config-manager-property -o key="mscm1" value="10.247.246.29"
litp create -p /software/items/config_manager/global_properties/property_mscm2 -t config-manager-property -o key="mscm2" value="10.247.246.30"
litp create -p /software/items/config_manager/global_properties/property_cmserv1 -t config-manager-property -o key="cmserv1" value="10.247.246.21"
litp create -p /software/items/config_manager/global_properties/property_cmserv2 -t config-manager-property -o key="cmserv2" value="10.247.246.22"
litp create -p /software/items/config_manager/global_properties/property_mspm1 -t config-manager-property -o key="mspm1" value="10.247.246.31"
litp create -p /software/items/config_manager/global_properties/property_mspm2 -t config-manager-property -o key="mspm2" value="10.247.246.32"
litp create -p /software/items/config_manager/global_properties/property_sec1 -t config-manager-property -o key="sec1" value="10.247.246.27"
litp create -p /software/items/config_manager/global_properties/property_sec2 -t config-manager-property -o key="sec2" value="10.247.246.28"
litp create -p /software/items/config_manager/global_properties/property_fmserv1 -t config-manager-property -o key="fmserv1" value="10.247.246.39"
litp create -p /software/items/config_manager/global_properties/property_fmserv2 -t config-manager-property -o key="fmserv2" value="10.247.246.40"
litp create -p /software/items/config_manager/global_properties/property_impexp1 -t config-manager-property -o key="impexp1" value="10.247.246.43"
litp create -p /software/items/config_manager/global_properties/property_impexp2 -t config-manager-property -o key="impexp2" value="10.247.246.44"
litp create -p /software/items/config_manager/global_properties/property_wpserv1 -t config-manager-property -o key="wpserv1" value="10.247.246.53"
litp create -p /software/items/config_manager/global_properties/property_wpserv2 -t config-manager-property -o key="wpserv2" value="10.247.246.54"
litp create -p /software/items/config_manager/global_properties/property_shmserv1 -t config-manager-property -o key="shmserv1" value="10.247.246.45"
litp create -p /software/items/config_manager/global_properties/property_shmserv2 -t config-manager-property -o key="shmserv2" value="10.247.246.46"
litp create -p /software/items/config_manager/global_properties/host_jgroups_bind_nic -t config-manager-property -o key="host_jgroups_bind_nic" value="bond0.2182"
litp create -p /software/items/config_manager/global_properties/host_internal_bind_nic -t config-manager-property -o key="host_internal_bind_nic" value="bond0"
litp create -p /software/items/config_manager/global_properties/jms_bind_address -t config-manager-property -o key="jms_bind_address" value="10.247.244.26"
litp create -p /software/items/config_manager/global_properties/NUMACTL_VERSANT -t config-manager-property -o key="NUMACTL_VERSANT" value="/usr/bin/numactl --physcpubind=0-13,16-23 --membind=0 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_ELASTICSEARCH -t config-manager-property -o key="NUMACTL_ELASTICSEARCH" value="/usr/bin/numactl --physcpubind=8-12,14-15,24 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_JMS -t config-manager-property -o key="NUMACTL_JMS" value="/usr/bin/numactl --physcpubind=4-7,25-28 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_OPENDJ -t config-manager-property -o key="NUMACTL_OPENDJ" value="/usr/bin/numactl --physcpubind=29 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_POSTGRES -t config-manager-property -o key="NUMACTL_POSTGRES" value="/usr/bin/numactl --physcpubind=30 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_MYSQL -t config-manager-property -o key="NUMACTL_MYSQL" value="/usr/bin/numactl --physcpubind=31 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_VERSANT_G9 -t config-manager-property -o key="NUMACTL_VERSANT_G9" value="/usr/bin/numactl --physcpubind=0-29 --membind=0 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_ELASTICSEARCH_G9 -t config-manager-property -o key="NUMACTL_ELASTICSEARCH_G9" value="/usr/bin/numactl --physcpubind=10-14,30-32 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_JMS_G9 -t config-manager-property -o key="NUMACTL_JMS_G9" value="/usr/bin/numactl --physcpubind=15-18,33-36 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_OPENDJ_G9 -t config-manager-property -o key="NUMACTL_OPENDJ_G9" value="/usr/bin/numactl --physcpubind=37 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_POSTGRES_G9 -t config-manager-property -o key="NUMACTL_POSTGRES_G9" value="/usr/bin/numactl --physcpubind=38 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/NUMACTL_MYSQL_G9 -t config-manager-property -o key="NUMACTL_MYSQL_G9" value="/usr/bin/numactl --physcpubind=39 --membind=1 -- "
litp create -p /software/items/config_manager/global_properties/httpd -t config-manager-property -o key="httpd" value="10.247.246.10,10.247.246.55"
litp create -p /software/items/config_manager/global_properties/openidm -t config-manager-property -o key="openidm" value="10.247.246.12"
litp create -p /software/items/config_manager/global_properties/sso -t config-manager-property -o key="sso" value="10.247.246.89,10.247.246.90"
litp create -p /software/items/config_manager/global_properties/uiserv -t config-manager-property -o key="uiserv" value="10.247.246.25,10.247.246.26"
litp create -p /software/items/config_manager/global_properties/wpserv -t config-manager-property -o key="wpserv" value="10.247.246.53,10.247.246.54"
litp create -p /software/items/config_manager/global_properties/eventbasedclient -t config-manager-property -o key="eventbasedclient" value="10.247.246.17,10.247.246.18"
litp create -p /software/items/config_manager/global_properties/medrouter -t config-manager-property -o key="medrouter" value="10.247.246.13,10.247.246.14"
litp create -p /software/items/config_manager/global_properties/supervc -t config-manager-property -o key="supervc" value="10.247.246.15,10.247.246.16"
litp create -p /software/items/config_manager/global_properties/cmserv -t config-manager-property -o key="cmserv" value="10.247.246.21,10.247.246.22"
litp create -p /software/items/config_manager/global_properties/mscm -t config-manager-property -o key="mscm" value="10.247.246.29,10.247.246.30"
litp create -p /software/items/config_manager/global_properties/mscmce -t config-manager-property -o key="mscmce" value="10.247.246.87,10.247.246.88"
litp create -p /software/items/config_manager/global_properties/comecimpolicy -t config-manager-property -o key="comecimpolicy" value="10.247.246.63,10.247.246.64"
litp create -p /software/items/config_manager/global_properties/cmrules -t config-manager-property -o key="cmrules" value="10.247.246.103,10.247.246.104"
litp create -p /software/items/config_manager/global_properties/netex -t config-manager-property -o key="netex" value="10.247.246.23,10.247.246.24"
litp create -p /software/items/config_manager/global_properties/secserv -t config-manager-property -o key="secserv" value="10.247.246.27,10.247.246.28"
litp create -p /software/items/config_manager/global_properties/sps -t config-manager-property -o key="sps" value="10.247.246.65,10.247.246.66"
litp create -p /software/items/config_manager/global_properties/pmserv -t config-manager-property -o key="pmserv" value="10.247.246.19,10.247.246.20"
litp create -p /software/items/config_manager/global_properties/mspm -t config-manager-property -o key="mspm" value="10.247.246.31,10.247.246.32"
litp create -p /software/items/config_manager/global_properties/fmalarmprocessing -t config-manager-property -o key="fmalarmprocessing" value="10.247.246.73,10.247.246.74"
litp create -p /software/items/config_manager/global_properties/fmhistory -t config-manager-property -o key="fmhistory" value="10.247.246.75,10.247.246.76"
litp create -p /software/items/config_manager/global_properties/fmserv -t config-manager-property -o key="fmserv" value="10.247.246.39,10.247.246.40"
litp create -p /software/items/config_manager/global_properties/msfm -t config-manager-property -o key="msfm" value="10.247.246.37,10.247.246.38"
litp create -p /software/items/config_manager/global_properties/nbalarmirp -t config-manager-property -o key="nbalarmirp" value="10.247.246.41,10.247.246.42"
litp create -p /software/items/config_manager/global_properties/visinamingnb -t config-manager-property -o key="visinamingnb" value="10.247.246.36"
litp create -p /software/items/config_manager/global_properties/solr -t config-manager-property -o key="solr" value="10.247.246.47"
litp create -p /software/items/config_manager/global_properties/bnsiserv -t config-manager-property -o key="bnsiserv" value="10.247.246.67,10.247.246.68"
litp create -p /software/items/config_manager/global_properties/fmx -t config-manager-property -o key="fmx" value="10.247.246.85,10.247.246.86"
litp create -p /software/items/config_manager/global_properties/emailservice -t config-manager-property -o key="emailservice" value="10.247.246.95"
litp create -p /software/items/config_manager/global_properties/dlms -t config-manager-property -o key="dlms" value="10.247.246.105,10.247.246.106"
litp create -p /software/items/config_manager/global_properties/map-service -t config-manager-property -o key="map-service" value="10.247.246.77,10.247.246.78"
litp create -p /software/items/config_manager/global_properties/impexpserv -t config-manager-property -o key="impexpserv" value="10.247.246.43,10.247.246.44"
litp create -p /software/items/config_manager/global_properties/shmserv -t config-manager-property -o key="shmserv" value="10.247.246.45,10.247.246.46"
litp create -p /software/items/config_manager/global_properties/kpiserv -t config-manager-property -o key="kpiserv" value="10.247.246.51,10.247.246.52"
litp create -p /software/items/config_manager/global_properties/visinamingsb -t config-manager-property -o key="visinamingsb" value="10.247.246.58"
litp create -p /software/items/config_manager/global_properties/apserv -t config-manager-property -o key="apserv" value="10.247.246.59,10.247.246.60"
litp create -p /software/items/config_manager/global_properties/msap -t config-manager-property -o key="msap" value="10.247.246.71,10.247.246.72"
litp create -p /software/items/config_manager/global_properties/lcmserv -t config-manager-property -o key="lcmserv" value="10.247.246.61,10.247.246.62"
litp create -p /software/items/config_manager/global_properties/ipsmserv -t config-manager-property -o key="ipsmserv" value="10.247.246.69,10.247.246.70"
litp create -p /software/items/config_manager/global_properties/mscmip -t config-manager-property -o key="mscmip" value="10.247.246.79,10.247.246.80"
litp create -p /software/items/config_manager/global_properties/pkiraserv -t config-manager-property -o key="pkiraserv" value="10.247.246.81,10.247.246.82"
litp create -p /software/items/config_manager/global_properties/mssnmpfm -t config-manager-property -o key="mssnmpfm" value="10.247.246.93,10.247.246.94"
litp create -p /software/items/config_manager/global_properties/said -t config-manager-property -o key="said" value="10.247.246.91,10.247.246.92"
litp create -p /software/items/config_manager/global_properties/itservices -t config-manager-property -o key="itservices" value="10.247.246.96,10.247.246.97"
litp create -p /software/items/config_manager/global_properties/dchistory -t config-manager-property -o key="dchistory" value="10.247.246.101,10.247.246.102"
litp create -p /software/items/config_manager/global_properties/httpd_instances -t config-manager-property -o key="httpd_instances" value="httpd-instance-1,httpd-instance-2"
litp create -p /software/items/config_manager/global_properties/sso_instances -t config-manager-property -o key="sso_instances" value="sso-instance-1,sso-instance-2"
litp create -p /software/items/config_manager/global_properties/mscmce1 -t config-manager-property -o key="mscmce1" value="10.247.246.87"
litp create -p /software/items/config_manager/global_properties/mscmce2 -t config-manager-property -o key="mscmce2" value="10.247.246.88"
litp create -p /software/items/config_manager/global_properties/comecimpolicy1 -t config-manager-property -o key="comecimpolicy1" value="10.247.246.63"
litp create -p /software/items/config_manager/global_properties/comecimpolicy2 -t config-manager-property -o key="comecimpolicy2" value="10.247.246.64"
litp create -p /software/items/config_manager/global_properties/cmrules1 -t config-manager-property -o key="cmrules1" value="10.247.246.103"
litp create -p /software/items/config_manager/global_properties/cmrules2 -t config-manager-property -o key="cmrules2" value="10.247.246.104"
litp create -p /software/items/config_manager/global_properties/netex1 -t config-manager-property -o key="netex1" value="10.247.246.23"
litp create -p /software/items/config_manager/global_properties/netex2 -t config-manager-property -o key="netex2" value="10.247.246.24"
litp create -p /software/items/config_manager/global_properties/sps1 -t config-manager-property -o key="sps1" value="10.247.246.65"
litp create -p /software/items/config_manager/global_properties/sps2 -t config-manager-property -o key="sps2" value="10.247.246.66"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_SURNAME -t config-manager-property -o key="PKI_EntityProfile_DN_SURNAME" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_COUNTRY_NAME -t config-manager-property -o key="PKI_EntityProfile_DN_COUNTRY_NAME" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_LOCALITY_NAME -t config-manager-property -o key="PKI_EntityProfile_DN_LOCALITY_NAME" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_STREET_ADDRESS -t config-manager-property -o key="PKI_EntityProfile_DN_STREET_ADDRESS" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_STATE -t config-manager-property -o key="PKI_EntityProfile_DN_STATE" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_ORGANIZATION_UNIT -t config-manager-property -o key="PKI_EntityProfile_DN_ORGANIZATION_UNIT" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_ORGANIZATION -t config-manager-property -o key="PKI_EntityProfile_DN_ORGANIZATION" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_DN_QUALIFIER -t config-manager-property -o key="PKI_EntityProfile_DN_DN_QUALIFIER" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_TITLE -t config-manager-property -o key="PKI_EntityProfile_DN_TITLE" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_GIVEN_NAME -t config-manager-property -o key="PKI_EntityProfile_DN_GIVEN_NAME" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/PKI_EntityProfile_DN_SERIAL_NUMBER -t config-manager-property -o key="PKI_EntityProfile_DN_SERIAL_NUMBER" value="couldbedefinedbyuser"
litp create -p /software/items/config_manager/global_properties/fmalarmprocessing1 -t config-manager-property -o key="fmalarmprocessing1" value="10.247.246.73"
litp create -p /software/items/config_manager/global_properties/fmalarmprocessing2 -t config-manager-property -o key="fmalarmprocessing2" value="10.247.246.74"
litp create -p /software/items/config_manager/global_properties/solrservice -t config-manager-property -o key="solrservice" value="10.247.246.47"
litp create -p /software/items/config_manager/global_properties/solrserviceport -t config-manager-property -o key="solrserviceport" value="8983"
litp create -p /software/items/config_manager/global_properties/bnsiserv1 -t config-manager-property -o key="bnsiserv1" value="10.247.246.67"
litp create -p /software/items/config_manager/global_properties/bnsiserv2 -t config-manager-property -o key="bnsiserv2" value="10.247.246.68"
litp create -p /software/items/config_manager/global_properties/fmx_rabbit_cluster_host_1 -t config-manager-property -o key="fmx_rabbit_cluster_host_1v" value="10.247.246.85"
litp create -p /software/items/config_manager/global_properties/fmx_rabbit_cluster_host_2 -t config-manager-property -o key="fmx_rabbit_cluster_host_2" value="10.247.246.86"
litp create -p /software/items/config_manager/global_properties/fmx_redis_cluster_host_1 -t config-manager-property -o key="fmx_redis_cluster_host_1" value="10.247.246.85"
litp create -p /software/items/config_manager/global_properties/fmx_redis_cluster_host_2 -t config-manager-property -o key="fmx_redis_cluster_host_2" value="10.247.246.86"
litp create -p /software/items/config_manager/global_properties/apserv1 -t config-manager-property -o key="apserv1" value="10.247.246.59"
litp create -p /software/items/config_manager/global_properties/apserv2 -t config-manager-property -o key="apserv2" value="10.247.246.60"
litp create -p /software/items/config_manager/global_properties/lcmserv1 -t config-manager-property -o key="lcmserv1" value="10.247.246.61"
litp create -p /software/items/config_manager/global_properties/lcmserv2 -t config-manager-property -o key="lcmserv2" value="10.247.246.62"
litp create -p /software/items/config_manager/global_properties/mscmip1 -t config-manager-property -o key="mscmip1" value="10.247.246.79"
litp create -p /software/items/config_manager/global_properties/mscmip2 -t config-manager-property -o key="mscmip2" value="10.247.246.80"
litp create -p /software/items/config_manager/global_properties/pkiraserv1 -t config-manager-property -o key="pkiraserv1" value="10.247.246.81"
litp create -p /software/items/config_manager/global_properties/pkiraserv2 -t config-manager-property -o key="pkiraserv2" value="10.247.246.82"
litp create -p /software/items/config_manager/global_properties/pkiraservPublicIP1 -t config-manager-property -o key="pkiraservPublicIP1" value="10.151.9.158"
litp create -p /software/items/config_manager/global_properties/pkiraservPublicIP2 -t config-manager-property -o key="pkiraservPublicIP2" value="10.151.9.159"
litp create -p /software/items/config_manager/global_properties/mssnmpfm1 -t config-manager-property -o key="mssnmpfm1" value="10.247.246.93"
litp create -p /software/items/config_manager/global_properties/mssnmpfm2 -t config-manager-property -o key="mssnmpfm2" value="10.247.246.94"



litp create -p /software/items/enm_utilities -t package -o name="ERICtorutilities_CXP9030570"
litp create -p /software/items/enm_eniq_integration -t package -o name="ERICeniqIntegrationService_CXP9031103" epoch=0
litp create -p /software/items/backup_restore_package -t package -o name="ERICbackuprestoreservice_CXP9031367"
litp create -p /software/items/backup_restore_ombs_package -t package -o name="ERICbackuprestoreserviceombs_CXP9031432"
litp create -p /software/items/pibscripts -t package -o name="ERICpibscripts_CXP9032212"
litp create -p /software/items/model_package -t package-list -o name="models"
litp create -p /software/items/model_package/packages/cppcmcimodel -t model-package -o name="ERICcppcmcimodel_CXP9031407"
litp create -p /software/items/model_package/packages/mediationcppconnectivityinfomodel -t model-package -o name="ERICmediationcppconnectivityinfomodel_CXP9031294"
litp create -p /software/items/model_package/packages/aicorewebmodel -t model-package -o name="ERICaicorewebmodel_CXP9030969"
litp create -p /software/items/model_package/packages/securityfunctionmodel -t model-package -o name="ERICsecurityfunctionmodel_CXP9031405"
litp create -p /software/items/model_package/packages/securitymodel -t model-package -o name="ERICsecuritymodel_CXP9030952"
litp create -p /software/items/model_package/packages/mediationtopconnectivityinfomodel -t model-package -o name="ERICmediationtopconnectivityinfomodel_CXP9031293"
litp create -p /software/items/model_package/packages/rncnetworkresourcemodel15b -t model-package -o name="ERICrncnetworkresourcemodel15b_CXP9031966"
litp create -p /software/items/model_package/packages/mediationrncnodemodelcommon -t model-package -o name="ERICmediationrncnodemodelcommon_CXP9032152"
litp create -p /software/items/model_package/packages/psmodels -t model-package -o name="ERICpsmodels_CXP9030922"
litp create -p /software/items/model_package/packages/pibmodel -t model-package -o name="ERICpibmodel_CXP9030858"
litp create -p /software/items/model_package/packages/webpushmodel -t model-package -o name="ERICwebpushmodel_CXP9031621"
litp create -p /software/items/model_package/packages/dpsconfmodels -t model-package -o name="ERICdpsconfmodels_CXP9030872"
litp create -p /software/items/model_package/packages/clialiasmodel -t model-package -o name="ERICclialiasmodel_CXP9031874"
litp create -p /software/items/model_package/packages/batchmodel -t model-package -o name="ERICbatchmodel_CXP9031518"
litp create -p /software/items/model_package/packages/upgradeindmodel -t model-package -o name="ERICupgradeindmodel_CXP9031718"
litp create -p /software/items/model_package/packages/hcservicemodel -t model-package -o name="ERIChcservicemodel_CXP9032088"
litp create -p /software/items/model_package/packages/medsdkeventmodels -t model-package -o name="ERICmedsdkeventmodels_CXP9030898"
litp create -p /software/items/model_package/packages/medcoreapichannelmodels -t model-package -o name="ERICmedcoreapichannelmodels_CXP9030899"
litp create -p /software/items/model_package/packages/sshhandlerflowconfig -t model-package -o name="ERICsshhandlerflowconfig_CXP9031056"
litp create -p /software/items/model_package/packages/sshhandlermodel -t model-package -o name="ERICsshhandlermodel_CXP9031029"
litp create -p /software/items/model_package/packages/sshhandlerflow -t model-package -o name="ERICsshhandlerflow_CXP9031030"
litp create -p /software/items/model_package/packages/nodesecuritymodel -t model-package -o name="ERICnodesecuritymodel_CXP9030968"
litp create -p /software/items/model_package/packages/shmmodels -t model-package -o name="ERICshmmodels_CXP9031349"
litp create -p /software/items/model_package/packages/addnodebootstrapmodels -t model-package -o name="ERICaddnodebootstrapmodels_CXP9031420"
litp create -p /software/items/model_package/packages/mocihandlermodel -t model-package -o name="ERICmocihandlermodel_CXP9030422"
litp create -p /software/items/model_package/packages/writenodeflowmodel -t model-package -o name="ERICwritenodeflowmodel_CXP9030945"
litp create -p /software/items/model_package/packages/erbsmediationconfigurationmodel -t model-package -o name="ERICerbsmediationconfigurationmodel_CXP9030429"
litp create -p /software/items/model_package/packages/readnonpersistedattributesflow -t model-package -o name="ERICreadnonpersistedattributesflow_CXP9031585"
litp create -p /software/items/model_package/packages/mediationservicesmodel -t model-package -o name="ERICmediationservicesmodel_CXP9031296"
litp create -p /software/items/model_package/packages/networkelementdefmodel -t model-package -o name="ERICnetworkelementdefmodel_CXP9031290"
litp create -p /software/items/model_package/packages/geolocationmodel -t model-package -o name="ERICgeolocationmodel_CXP9031964"
litp create -p /software/items/model_package/packages/syncnodeevent -t model-package -o name="ERICsyncnodeevent_CXP9031195"
litp create -p /software/items/model_package/packages/syncnodeflowmodel -t model-package -o name="ERICsyncnodeflowmodel_CXP9030696"
litp create -p /software/items/model_package/packages/inbounddpshandlermodel -t model-package -o name="ERICinbounddpshandlermodel_CXP9030733"
litp create -p /software/items/model_package/packages/syncnodemocihandlermodel -t model-package -o name="ERICsyncnodemocihandlermodel_CXP9030741"
litp create -p /software/items/model_package/packages/subscriptionflow -t model-package -o name="ERICsubscriptionflow_CXP9031209"
litp create -p /software/items/model_package/packages/subscriptioncreationhandlermodel -t model-package -o name="ERICsubscriptioncreationhandlermodel_CXP9031210"
litp create -p /software/items/model_package/packages/notificationhandlingflow -t model-package -o name="ERICnotificationhandlingflow_CXP9031202"
litp create -p /software/items/model_package/packages/notificationreceiverhandlermodel -t model-package -o name="ERICnotificationreceiverhandlermodel_CXP9031203"
litp create -p /software/items/model_package/packages/networkconnectorconfigmodels -t model-package -o name="ERICnetworkconnectorconfigmodels_CXP9031370"
litp create -p /software/items/model_package/packages/subscriptionvalidationflow -t model-package -o name="ERICsubscriptionvalidationflow_CXP9031214"
litp create -p /software/items/model_package/packages/subscriptionvalidationhandlermodel -t model-package -o name="ERICsubscriptionvalidationhandlermodel_CXP9031215"
litp create -p /software/items/model_package/packages/networkelementcmdefmodel -t model-package -o name="ERICnetworkelementcmdefmodel_CXP9031291"
litp create -p /software/items/model_package/packages/osstopmodel -t model-package -o name="ERICosstopmodel_CXP9031292"
litp create -p /software/items/model_package/packages/mediationerbsnodemodelcommon -t model-package -o name="ERICmediationerbsnodemodelcommon_CXP9032151"
litp create -p /software/items/model_package/packages/mediationerbsnodemodel16b -t model-package -o name="ERICmediationerbsnodemodel16b_CXP9032523"
litp create -p /software/items/model_package/packages/mediationerbsnodemodel16a -t model-package -o name="ERICmediationerbsnodemodel16a_CXP9032349"
litp create -p /software/items/model_package/packages/mediationerbsnodemodel15b -t model-package -o name="ERICmediationerbsnodemodel15b_CXP9031712"
litp create -p /software/items/model_package/packages/mediationerbsnodemodel14b -t model-package -o name="ERICmediationerbsnodemodel14b_CXP9030987"
litp create -p /software/items/model_package/packages/mediationerbsnodemodel14a -t model-package -o name="ERICmediationerbsnodemodel14a_CXP9030986"
litp create -p /software/items/model_package/packages/mediationerbsnodemodel13b -t model-package -o name="ERICmediationerbsnodemodel13b_CXP9030985"
litp create -p /software/items/model_package/packages/mediationerbsnodemodel13a -t model-package -o name="ERICmediationerbsnodemodel13a_CXP9030984"
litp create -p /software/items/model_package/packages/mediationmgwnodemodel15b -t model-package -o name="ERICmediationmgwnodemodel15b_CXP9032455"
litp create -p /software/items/model_package/packages/mediationmgwnodemodelcommon -t model-package -o name="ERICmediationmgwnodemodelcommon_CXP9032434"
litp create -p /software/items/model_package/packages/sgsnmmenetworkresourcemodel14b -t model-package -o name="ERICsgsnmmenetworkresourcemodel14b_CXP9031369"
litp create -p /software/items/model_package/packages/mediationsgsnmmenodemodelcommon -t model-package -o name="ERICmediationsgsnmmenodemodelcommon_CXP9032153"
litp create -p /software/items/model_package/packages/sgsnmmenetworkresourcemodel15a -t model-package -o name="ERICsgsnmmenetworkresourcemodel15a_CXP9031713"
litp create -p /software/items/model_package/packages/sgsnmmenetworkresourcemodel15b -t model-package -o name="ERICsgsnmmenetworkresourcemodel15b_CXP9032044"
litp create -p /software/items/model_package/packages/commodelsr5_0 -t model-package -o name="ERICcommodelsr5.0_CXP9031865"
litp create -p /software/items/model_package/packages/msrbsv2networkresourcemodel15b -t model-package -o name="ERICmsrbsv2networkresourcemodel15b_CXP9031504"
litp create -p /software/items/model_package/packages/msrbsv2nodemodelcommon -t model-package -o name="ERICmsrbsv2nodemodelcommon_CXP9032227"
litp create -p /software/items/model_package/packages/commodelsr5_1 -t model-package -o name="ERICcommodelsr5.1_CXP9032416"
litp create -p /software/items/model_package/packages/msrbsv2networkresourcemodel16a -t model-package -o name="ERICmsrbsv2networkresourcemodel16a_CXP9032375"
litp create -p /software/items/model_package/packages/sgsnmmewritenodeflowmodels -t model-package -o name="ERICsgsnmmewritenodeflowmodels_CXP9032017"
litp create -p /software/items/model_package/packages/cbanetconfwritecontrollermodel -t model-package -o name="ERICcbanetconfwritecontrollermodel_CXP9032025"
litp create -p /software/items/model_package/packages/radionodewritenodeflowmodels -t model-package -o name="ERICradionodewritenodeflowmodels_CXP9032354"
litp create -p /software/items/model_package/packages/mediationcomconnectivityinfomodel -t model-package -o name="ERICmediationcomconnectivityinfomodel_CXP9031276"
litp create -p /software/items/model_package/packages/sgsnmmemedconfiguration -t model-package -o name="ERICsgsnmmemedconfiguration_CXP9031615"
litp create -p /software/items/model_package/packages/radionodemediationconfiguration -t model-package -o name="ERICradionodemediationconfiguration_CXP9031903"
litp create -p /software/items/model_package/packages/comcmheartbeatsupervisionflow -t model-package -o name="ERICcomcmheartbeatsupervisionflow_CXP9031584"
litp create -p /software/items/model_package/packages/comecimcmheartbeatsuphandlermodel -t model-package -o name="ERICcomecimcmheartbeatsuphandlermodel_CXP9031587"
litp create -p /software/items/model_package/packages/ecimcmheartbeatsupervisionflow -t model-package -o name="ERICecimcmheartbeatsupervisionflow_CXP9031586"
litp create -p /software/items/model_package/packages/ecimnotifheartbeathandlermodel -t model-package -o name="ERICecimnotifheartbeathandlermodel_CXP9031703"
litp create -p /software/items/model_package/packages/cbanodeevents -t model-package -o name="ERICcbanodeevents_CXP9031762"
litp create -p /software/items/model_package/packages/comecimcmdeltasyncflowmodel -t model-package -o name="ERICcomecimcmdeltasyncflowmodel_CXP9031759"
litp create -p /software/items/model_package/packages/comecimcmdeltasynchandlermodel -t model-package -o name="ERICcomecimcmdeltasynchandlermodel_CXP9031760"
litp create -p /software/items/model_package/packages/comecimcmpreparesubshandlermodel -t model-package -o name="ERICcomecimcmpreparesubshandlermodel_CXP9032033"
litp create -p /software/items/model_package/packages/comecimcmsubscriptionhandlermodel -t model-package -o name="ERICcomecimcmsubscriptionhandlermodel_CXP9031598"
litp create -p /software/items/model_package/packages/comecimcreatesubscriptionflowmodel -t model-package -o name="ERICcomecimcreatesubscriptionflowmodel_CXP9031676"
litp create -p /software/items/model_package/packages/comecimdeletesubscriptionflowmodel -t model-package -o name="ERICcomecimdeletesubscriptionflowmodel_CXP9031677"
litp create -p /software/items/model_package/packages/comecimdeletesubshandlermodel -t model-package -o name="ERICcomecimdeletesubshandlermodel_CXP9031684"
litp create -p /software/items/model_package/packages/comecimnotifsupervisionhandlermodel -t model-package -o name="ERICcomecimnotifsupervisionhandlermodel_CXP9031678"
litp create -p /software/items/model_package/packages/ecimnotificationhandlingflowmodel -t model-package -o name="ERICecimnotificationhandlingflowmodel_CXP9031675"
litp create -p /software/items/model_package/packages/sgsncreatesubsflowmodel -t model-package -o name="ERICsgsncreatesubsflowmodel_CXP9032000"
litp create -p /software/items/model_package/packages/sgsndeletesubsflowmodel -t model-package -o name="ERICsgsndeletesubsflowmodel_CXP9032037"
litp create -p /software/items/model_package/packages/notificationcachedefinitionmodels -t model-package -o name="ERICnotificationcachedefinitionmodels_CXP9032208"
litp create -p /software/items/model_package/packages/cbacmsyncnodeflowmodels -t model-package -o name="ERICcbacmsyncnodeflowmodels_CXP9031502"
litp create -p /software/items/model_package/packages/cbacmsyncnodehandlermodel -t model-package -o name="ERICcbacmsyncnodehandlermodel_CXP9031501"
litp create -p /software/items/model_package/packages/comecimcmfiltergethandlermodel -t model-package -o name="ERICcomecimcmfiltergethandlermodel_CXP9032146"
litp create -p /software/items/model_package/packages/radionodecmreadnodeflow -t model-package -o name="ERICradionodecmreadnodeflow_CXP9032143"
litp create -p /software/items/model_package/packages/sgsnmmecmreadnodeflow -t model-package -o name="ERICsgsnmmecmreadnodeflow_CXP9032144"
litp create -p /software/items/model_package/packages/netconfperiodictaskhandlermodel -t model-package -o name="ERICnetconfperiodictaskhandlermodel_CXP9031879"
litp create -p /software/items/model_package/packages/netconfsessionsubshandlermodel -t model-package -o name="ERICnetconfsessionsubshandlermodel_CXP9031878"
litp create -p /software/items/model_package/packages/sgsnmmenetconfpreconnhandmodel -t model-package -o name="ERICsgsnmmenetconfpreconnhandmodel_CXP9031947"
litp create -p /software/items/model_package/packages/cbanetconfconnecthandlermodel -t model-package -o name="ERICcbanetconfconnecthandlermodel_CXP9031346"
litp create -p /software/items/model_package/packages/cbacmnetconfhandlermodel -t model-package -o name="ERICcbacmnetconfhandlermodel_CXP9031222"
litp create -p /software/items/model_package/packages/cbaconfigurationmodel -t model-package -o name="ERICcbaconfigurationmodel_CXP9031361"
litp create -p /software/items/model_package/packages/cbanetconfdisconnecthandlermodel -t model-package -o name="ERICcbanetconfdisconnecthandlermodel_CXP9031348"
litp create -p /software/items/model_package/packages/netconfsessionbuilderhandmodel -t model-package -o name="ERICnetconfsessionbuilderhandmodel_CXP9032079"
litp create -p /software/items/model_package/packages/netconfsessiondestroyerhandmodel -t model-package -o name="ERICnetconfsessiondestroyerhandmodel_CXP9032256"
litp create -p /software/items/model_package/packages/netconfsessionreleaserhandmodel -t model-package -o name="ERICnetconfsessionreleaserhandmodel_CXP9032255"
litp create -p /software/items/model_package/packages/sshcredentialsmanagerhandlermodel -t model-package -o name="ERICsshcredentialsmanagerhandlermodel_CXP9032067"
litp create -p /software/items/model_package/packages/sshtransportconnecthandlermodel -t model-package -o name="ERICsshtransportconnecthandlermodel_CXP9032168"
litp create -p /software/items/model_package/packages/netconfinboundconfighandlermodel -t model-package -o name="ERICnetconfinboundconfighandlermodel_CXP9032317"
litp create -p /software/items/model_package/packages/sgsnmmesecuritymediationconfig -t model-package -o name="ERICsgsnmmesecuritymediationconfig_CXP9032057"
litp create -p /software/items/model_package/packages/sgsnmmesecuritysshcommandflow -t model-package -o name="ERICsgsnmmesecuritysshcommandflow_CXP9032060"
litp create -p /software/items/model_package/packages/sshcommandhandlermodel -t model-package -o name="ERICsshcommandhandlermodel_CXP9032058"
litp create -p /software/items/model_package/packages/sgsnmmecommandhandlermodel -t model-package -o name="ERICsgsnmmecommandhandlermodel_CXP9032061"
litp create -p /software/items/model_package/packages/authenticationfailureevent -t model-package -o name="ERICauthenticationfailureevent_CXP9032066"
litp create -p /software/items/model_package/packages/authenticationfailureflow -t model-package -o name="ERICauthenticationfailureflow_CXP9032063"
litp create -p /software/items/model_package/packages/authenticationfailurehandlermodel -t model-package -o name="ERICauthenticationfailurehandlermodel_CXP9032064"
litp create -p /software/items/model_package/packages/fmmediationeventmodel -t model-package -o name="ERICfmmediationeventmodel_CXP9030672"
litp create -p /software/items/model_package/packages/er6000cimodel -t model-package -o name="ERICer6000cimodel_CXP9031842"
litp create -p /software/items/model_package/packages/er6000nodemodelcommon -t model-package -o name="ERICer6000nodemodelcommon_CXP9032077"
litp create -p /software/items/model_package/packages/er6274nodemodelcommon -t model-package -o name="ERICer6274nodemodelcommon_CXP9032483"
litp create -p /software/items/model_package/packages/er6672nodemodelcommon -t model-package -o name="ERICer6672nodemodelcommon_CXP9032478"
litp create -p /software/items/model_package/packages/er6675nodemodelcommon -t model-package -o name="ERICer6675nodemodelcommon_CXP9032484"
litp create -p /software/items/model_package/packages/upgradeindhttpfilehandlermodel -t model-package -o name="ERICupgradeindhttpfilehandlermodel_CXP9031770"
litp create -p /software/items/model_package/packages/upgradeindcppretrmimhandlersmodel -t model-package -o name="ERICupgradeindcppretrmimhandlersmodel_CXP9031766"
litp create -p /software/items/model_package/packages/upgradeindcppretrievemimflow -t model-package -o name="ERICupgradeindcppretrievemimflow_CXP9031724"
litp create -p /software/items/model_package/packages/ftphandlermodel -t model-package -o name="ERICftphandlermodel_CXP9030847"
litp create -p /software/items/model_package/packages/upgradeindecimretrmhandlersmodel -t model-package -o name="ERICupgradeindecimretrmhandlersmodel_CXP9031768"
litp create -p /software/items/model_package/packages/upgradeindecimretrievemimflow -t model-package -o name="ERICupgradeindecimretrievemimflow_CXP9031728"
litp create -p /software/items/model_package/packages/upgradeindcomecimretrmimhrsmodel -t model-package -o name="ERICupgradeindcomecimretrmimhrsmodel_CXP9032276"
litp create -p /software/items/model_package/packages/erbshchandlerflows -t model-package -o name="ERICerbshchandlerflows_CXP9032090"
litp create -p /software/items/model_package/packages/erbshandlermodels -t model-package -o name="ERICerbshandlermodels_CXP9032091"
litp create -p /software/items/model_package/packages/minilinkindoornodemodelcommon -t model-package -o name="ERICminilinkindoornodemodelcommon_CXP9032236"
litp create -p /software/items/model_package/packages/minilinkindoorcimodel -t model-package -o name="ERICminilinkindoorcimodel_CXP9032238"
litp create -p /software/items/model_package/packages/minilinkindoorcmmediationconf -t model-package -o name="ERICminilinkindoorcmmediationconf_CXP9032239"
litp create -p /software/items/model_package/packages/minilinkoutdoornodemodelcom -t model-package -o name="ERICminilinkoutdoornodemodelcom_CXP9032240"
litp create -p /software/items/model_package/packages/minilinkoutdoorcimodel -t model-package -o name="ERICminilinkoutdoorcimodel_CXP9032242"
litp create -p /software/items/model_package/packages/minilinkoutdoorcmmedconfig -t model-package -o name="ERICminilinkoutdoorcmmedconfig_CXP9032243"
litp create -p /software/items/model_package/packages/softwaresynceventmodel -t model-package -o name="ERICsoftwaresynceventmodel_CXP9032514"
litp create -p /software/items/model_package/packages/cppsoftwaresyncflowmodel -t model-package -o name="ERICcppsoftwaresyncflowmodel_CXP9032510"
litp create -p /software/items/model_package/packages/commonsoftwaresynchandlermodel -t model-package -o name="ERICcommonsoftwaresynchandlermodel_CXP9032508"
litp create -p /software/items/model_package/packages/cppsoftwaresynchandlermodel -t model-package -o name="ERICcppsoftwaresynchandlermodel_CXP9032507"
litp create -p /software/items/model_package/packages/mediationsgsnmmenodemodel16a -t model-package -o name="ERICmediationsgsnmmenodemodel16a_CXP9032284"
litp create -p /software/items/model_package/packages/commodelsr60 -t model-package -o name="ERICcommodelsr60_CXP9032536"
litp create -p /software/items/model_package/packages/radionodenodemodel16b -t model-package -o name="ERICradionodenodemodel16b_CXP9032534"
litp create -p /software/items/model_package/packages/tlscredentialsmanagerhandlermodel -t model-package -o name="ERICtlscredentialsmanagerhandlermodel_CXP9032281"
litp create -p /software/items/model_package/packages/cmrouterpolicymodel -t model-package -o name="ERICcmrouterpolicymodel_CXP9032342"
litp create -p /software/items/model_package/packages/er6000routerpolicymodel -t model-package -o name="ERICer6000routerpolicymodel_CXP9032576"
litp create -p /software/items/model_package/packages/comecimcmrouterpolicymodel -t model-package -o name="ERICcomecimcmrouterpolicymodel_CXP9032613"
litp create -p /software/items/model_package/packages/networkexplorermodels -t model-package -o name="ERICnetworkexplorermodels_CXP9030552"
litp create -p /software/items/model_package/packages/smrsservicemodel -t model-package -o name="ERICsmrsservicemodel_CXP9030970"
litp create -p /software/items/model_package/packages/wfsmodel -t model-package -o name="ERICwfsmodel_CXP9031037"
litp create -p /software/items/model_package/packages/policyenginemodel -t model-package -o name="ERICpolicyenginemodel_CXP9031944"
litp create -p /software/items/model_package/packages/fmprocessedeventmodel -t model-package -o name="ERICfmprocessedeventmodel_CXP9030673"
litp create -p /software/items/model_package/packages/targethandlersmodels -t model-package -o name="ERICtargethandlersmodels_CXP9032666"
litp create -p /software/items/model_package/packages/genericidentitymgmtmodel -t model-package -o name="ERICgenericidentitymgmtmodel_CXP9032610"
litp create -p /software/items/model_package/packages/ssoutilitiesmodel -t model-package -o name="ERICssoutilitiesmodel_CXP9032644"
litp create -p /software/items/model_package/packages/pkimanagerconfigmodel -t model-package -o name="ERICpkimanagerconfigmodel_CXP9032043"
litp create -p /software/items/model_package/packages/pkicdpsmodel -t model-package -o name="ERICpkicdpsmodel_CXP9032532"
litp create -p /software/items/model_package/packages/pkicoremodel -t model-package -o name="ERICpkicoremodel_CXP9032529"
litp create -p /software/items/model_package/packages/pkiracmpmodel -t model-package -o name="ERICpkiracmpmodel_CXP9032010"
litp create -p /software/items/model_package/packages/pmfunctionmodel -t model-package -o name="ERICpmfunctionmodel_CXP9031819"
litp create -p /software/items/model_package/packages/pmiccorbahandlermodel -t model-package -o name="ERICpmiccorbahandlermodel_CXP9030591"
litp create -p /software/items/model_package/packages/pmicdpshandlermodel -t model-package -o name="ERICpmicdpshandlermodel_CXP9030598"
litp create -p /software/items/model_package/packages/pmicfilecollectionhandlersmodels -t model-package -o name="ERICpmicfilecollectionhandlersmodels_CXP9030845"
litp create -p /software/items/model_package/packages/pmicinitiationflowmodel -t model-package -o name="ERICpmicinitiationflowmodel_CXP9030608"
litp create -p /software/items/model_package/packages/pmicfilecollection -t model-package -o name="ERICpmicfilecollection_CXP9030837"
litp create -p /software/items/model_package/packages/mediationconfigurationmodel -t model-package -o name="ERICmediationconfigurationmodel_CXP9030610"
litp create -p /software/items/model_package/packages/pmicmodel -t model-package -o name="ERICpmicmodel_CXP9030403"
litp create -p /software/items/model_package/packages/sgsnmmepmpollingflow -t model-package -o name="ERICsgsnmmepmpollingflow_CXP9032032"
litp create -p /software/items/model_package/packages/comecimpmpollingflow -t model-package -o name="ERICcomecimpmpollingflow_CXP9031690"
litp create -p /software/items/model_package/packages/comecimpmpollinghandlermodel -t model-package -o name="ERICcomecimpmpollinghandlermodel_CXP9031691"
litp create -p /software/items/model_package/packages/ecimpmoperationsflow -t model-package -o name="ERICecimpmoperationsflow_CXP9031687"
litp create -p /software/items/model_package/packages/ecimpmoperationshandlermodel -t model-package -o name="ERICecimpmoperationshandlermodel_CXP9031688"
litp create -p /software/items/model_package/packages/comecimpmfilecollectionflow -t model-package -o name="ERICcomecimpmfilecollectionflow_CXP9031984"
litp create -p /software/items/model_package/packages/comecimpmfilecollectsetuphandmodel -t model-package -o name="ERICcomecimpmfilecollectsetuphandmodel_CXP9031985"
litp create -p /software/items/model_package/packages/sgsnmmepmmediationconfigmodel -t model-package -o name="ERICsgsnmmepmmediationconfigmodel_CXP9031696"
litp create -p /software/items/model_package/packages/comecimpmoperationsflow -t model-package -o name="ERICcomecimpmoperationsflow_CXP9032030"
litp create -p /software/items/model_package/packages/comecimpmoperhandlermodel -t model-package -o name="ERICcomecimpmoperhandlermodel_CXP9032218"
litp create -p /software/items/model_package/packages/radionodepmmediationconfigmodel -t model-package -o name="ERICradionodepmmediationconfigmodel_CXP9032029"
litp create -p /software/items/model_package/packages/comecimpmcompleteoperationsflow -t model-package -o name="ERICcomecimpmcompleteoperationsflow_CXP9032031"
litp create -p /software/items/model_package/packages/comecimpmevents -t model-package -o name="ERICcomecimpmevents_CXP9032379"
litp create -p /software/items/model_package/packages/ERICcomecimpmevents_CXP9032379 -t model-package -o name="ERICsgsnmmepmfilecollectionflow_CXP9032283"
litp create -p /software/items/model_package/packages/comecimpmasyncoperhandlermodel -t model-package -o name="ERICcomecimpmasyncoperhandlermodel_CXP9032166"
litp create -p /software/items/model_package/packages/ecimpmeventsmoperationhandlrmodel -t model-package -o name="ERICecimpmeventsmoperationhandlrmodel_CXP9032126"
litp create -p /software/items/model_package/packages/pmicebminitiationhandlermodel -t model-package -o name="ERICpmicebminitiationhandlermodel_CXP9032475"
litp create -p /software/items/model_package/packages/dpsdataretrievalsetuphandlermodel -t model-package -o name="ERICdpsdataretrievalsetuphandlermodel_CXP9032388"
litp create -p /software/items/model_package/packages/erbscpppmiccollectionhandlersmodel -t model-package -o name="ERICerbscpppmiccollectionhandlersmodel_CXP9032391"
litp create -p /software/items/model_package/packages/pmiccelltraceinitsetuphndlrmodels -t model-package -o name="ERICpmiccelltraceinitsetuphndlrmodels_CXP9032398"
litp create -p /software/items/model_package/packages/pmicpredefstatsinitsetuphndlrmodels -t model-package -o name="ERICpmicpredefstatsinitsetuphndlrmodels_CXP9032399"
litp create -p /software/items/model_package/packages/pmicstatsinitsetuphndlrsmodels -t model-package -o name="ERICpmicstatsinitsetuphndlrsmodels_CXP9032397"
litp create -p /software/items/model_package/packages/sgsnmmepmhandlersmodel -t model-package -o name="ERICsgsnmmepmhandlersmodel_CXP9032611"
litp create -p /software/items/model_package/packages/pmiccommonscannerhandlermodel -t model-package -o name="ERICpmiccommonscannerhandlermodel_CXP9032590"
litp create -p /software/items/model_package/packages/alarmpersistencemodel -t model-package -o name="ERICalarmpersistencemodel_CXP9030634"
litp create -p /software/items/model_package/packages/fmfmxmodel -t model-package -o name="ERICfmfmxmodel_CXP9031623"
litp create -p /software/items/model_package/packages/fmcorbamediationconfig -t model-package -o name="ERICfmcorbamediationconfig_CXP9030689"
litp create -p /software/items/model_package/packages/cppalarmsupervisionflowmodel -t model-package -o name="ERICcppalarmsupervisionflowmodel_CXP9030679"
litp create -p /software/items/model_package/packages/cppalarmsupervisionhandlermodel -t model-package -o name="ERICcppalarmsupervisionhandlermodel_CXP9030680"
litp create -p /software/items/model_package/packages/corbainterfacemodel -t model-package -o name="ERICcorbainterfacemodel_CXP9031151"
litp create -p /software/items/model_package/packages/solrloadschedulemodel -t model-package -o name="ERICsolrloadschedulemodel_CXP9031934"
litp create -p /software/items/model_package/packages/dlmsconfigurationmodel -t model-package -o name="ERICdlmsconfigurationmodel_CXP9032634"
litp create -p /software/items/model_package/packages/eniqtopologyservicemodel -t model-package -o name="ERICeniqtopologyservicemodel_CXP9031298"
litp create -p /software/items/model_package/packages/predefinedfiltermodel -t model-package -o name="ERICpredefinedfiltermodel_CXP9032383"
litp create -p /software/items/model_package/packages/shmfunctionmodel -t model-package -o name="ERICshmfunctionmodel_CXP9031388"
litp create -p /software/items/model_package/packages/shmjobmodel -t model-package -o name="ERICshmjobmodel_CXP9031092"
litp create -p /software/items/model_package/packages/cppinventorymodel -t model-package -o name="ERICcppinventorymodel_CXP9030632"
litp create -p /software/items/model_package/packages/inventoryhandlermodel -t model-package -o name="ERICinventoryhandlermodel_CXP9031350"
litp create -p /software/items/model_package/packages/cppinventorymediationconfigmodel -t model-package -o name="ERICcppinventorymediationconfigmodel_CXP9030620"
litp create -p /software/items/model_package/packages/upgradepackagemodel -t model-package -o name="ERICupgradepackagemodel_CXP9030915"
litp create -p /software/items/model_package/packages/shmmodelextension -t model-package -o name="ERICshmmodelextension_CXP9031197"

litp create -p /software/items/model_package/packages/licensekeyinfomodel -t model-package -o name="ERIClicensekeyinfomodel_CXP9031107"
litp create -p /software/items/model_package/packages/cppinventoryflowmodel -t model-package -o name="ERICcppinventoryflowmodel_CXP9030622"
litp create -p /software/items/model_package/packages/kpicalculationflowmodel -t model-package -o name="ERICkpicalculationflowmodel_CXP9031710"
litp create -p /software/items/model_package/packages/apdatacore -t model-package -o name="ERICapdatacore_CXP9030534"
litp create -p /software/items/model_package/packages/apdatamacro -t model-package -o name="ERICapdatamacro_CXP9030537"
litp create -p /software/items/model_package/packages/apmodelecim -t model-package -o name="ERICapmodelecim_CXP9032498"
litp create -p /software/items/model_package/packages/nodediscoveryflowmodel -t model-package -o name="ERICnodediscoveryflowmodel_CXP9031392"
litp create -p /software/items/model_package/packages/nodediscoveryhandlersmodel -t model-package -o name="ERICnodediscoveryhandlersmodel_CXP9031395"
litp create -p /software/items/model_package/packages/apmediationmodel -t model-package -o name="ERICapmediationmodel_CXP9032337"
litp create -p /software/items/model_package/packages/licensecontrolmonitoringmodel -t model-package -o name="ERIClicensecontrolmonitoringmodel_CXP9031453"
litp create -p /software/items/model_package/packages/ipsmtemplatemanagermodel -t model-package -o name="ERICipsmtemplatemanagermodel_CXP9031442"
litp create -p /software/items/model_package/packages/ipsmservicedefinitionmodel -t model-package -o name="ERICipsmservicedefinitionmodel_CXP9031991"
litp create -p /software/items/model_package/packages/ipsmservicemanagermodel -t model-package -o name="ERICipsmservicemanagermodel_CXP9031993"
litp create -p /software/items/model_package/packages/ipnediscoverymodel -t model-package -o name="ERICipnediscoverymodel_CXP9032136"
litp create -p /software/items/model_package/packages/activityservicemodel -t model-package -o name="ERICactivityservicemodel_CXP9031444"
litp create -p /software/items/model_package/packages/er6000mediationconfiguration -t model-package -o name="ERICer6000mediationconfiguration_CXP9031843"
litp create -p /software/items/model_package/packages/mediationiptransportchannelmodels -t model-package -o name="ERICmediationiptransportchannelmodels_CXP9032406"
litp create -p /software/items/model_package/packages/er6000nodemodel16a -t model-package -o name="ERICer6000nodemodel16a_CXP9032075"
litp create -p /software/items/model_package/packages/er6672nodemodel16a -t model-package -o name="ERICer6672nodemodel16a_CXP9032479"
litp create -p /software/items/model_package/packages/netconfecimsyncnodehandlermodel -t model-package -o name="ERICnetconfecimsyncnodehandlermodel_CXP9032367"
litp create -p /software/items/model_package/packages/er6000syncnodeflow -t model-package -o name="ERICer6000syncnodeflow_CXP9032360"
litp create -p /software/items/model_package/packages/er6000configurationmodel -t model-package -o name="ERICer6000configurationmodel_CXP9032374"
litp create -p /software/items/model_package/packages/netconfecimoperationflow -t model-package -o name="ERICnetconfecimoperationflow_CXP9032361"
litp create -p /software/items/model_package/packages/ipnesnmpscanflo -t model-package -o name="ERICipnesnmpscanflow_CXP9032287"
litp create -p /software/items/model_package/packages/ipnediscoveryhandlermodel -t model-package -o name="ERICipnediscoveryhandlermodel_CXP9032433"
litp create -p /software/items/model_package/packages/netconfyangsyncnodehandlermodel -t model-package -o name="ERICnetconfyangsyncnodehandlermodel_CXP9032368"
litp create -p /software/items/model_package/packages/netconfyangoperationhandlermodel -t model-package -o name="ERICnetconfyangoperationhandlermodel_CXP9032369"
litp create -p /software/items/model_package/packages/netconfyangoperationflow -t model-package -o name="ERICnetconfyangoperationflow_CXP9032362"
litp create -p /software/items/model_package/packages/iposcmnotificationhandlingflow -t model-package -o name="ERICiposcmnotificationhandlingflow_CXP9032473"
litp create -p /software/items/model_package/packages/iposcmheartbtsuphandlermodel -t model-package -o name="ERICiposcmheartbtsuphandlermodel_CXP9032464"
litp create -p /software/items/model_package/packages/iposcmheartbtsupflow -t model-package -o name="ERICiposcmheartbtsupflow_CXP9032447"
litp create -p /software/items/model_package/packages/iposcmsubflow -t model-package -o name="ERICiposcmsubflow_CXP9032446"
litp create -p /software/items/model_package/packages/iposcmsubhandlermodel -t model-package -o name="ERICiposcmsubhandlermodel_CXP9032463"
litp create -p /software/items/model_package/packages/pkirascepmodel -t model-package -o name="ERICpkirascepmodel_CXP9032006"
litp create -p /software/items/model_package/packages/pkiratdpsmodel -t model-package -o name="ERICpkiratdpsmodel_CXP9032425"
litp create -p /software/items/model_package/packages/snmpfmhandlermodel -t model-package -o name="ERICsnmpfmhandlermodel_CXP9031547"
litp create -p /software/items/model_package/packages/snmpfmflowmodel -t model-package -o name="ERICsnmpfmflowmodel_CXP9031549"
litp create -p /software/items/model_package/packages/ecimnetconffmflowmodel -t model-package -o name="ERICecimnetconffmflowmodel_CXP9032249"
litp create -p /software/items/model_package/packages/sgsnmmenetconffmflowmodel -t model-package -o name="ERICsgsnmmenetconffmflowmodel_CXP9032246"
litp create -p /software/items/model_package/packages/snmpfmchannelmodels -t model-package -o name="ERICsnmpfmchannelmodels_CXP9032452"
litp create -p /software/items/model_package/packages/minilinkindoorfmmediationconf -t model-package -o name="ERICminilinkindoorfmmediationconf_CXP9032306"
litp create -p /software/items/model_package/packages/minilinkindoortargetdestflow -t model-package -o name="ERICminilinkindoortargetdestflow_CXP9032347"
litp create -p /software/items/model_package/packages/er6000fmmediationconfiguration -t model-package -o name="ERICer6000fmmediationconfiguration_CXP9032382"
litp create -p /software/items/model_package/packages/er6000snmpfmmodel -t model-package -o name="ERICer6000snmpfmmodel_CXP9032380"
litp create -p /software/items/model_package/packages/er6000snmpfmhandlermodel -t model-package -o name="ERICer6000snmpfmhandlermodel_CXP9032403"
litp create -p /software/items/model_package/packages/msrbsv2fmmediationconfig -t model-package -o name="ERICmsrbsv2fmmediationconfig_CXP9031733"
litp create -p /software/items/model_package/packages/wppsgsnmmefmmediationconfigmodel -t model-package -o name="ERICwppsgsnmmefmmediationconfigmodel_CXP9031784"
litp create -p /software/items/model_package/packages/ecimnetconffmhandlermodel -t model-package -o name="ERICecimnetconffmhandlermodel_CXP9032248"
litp create -p /software/items/model_package/packages/sgsnmmenetconffmhandlermodel -t model-package -o name="ERICsgsnmmenetconffmhandlermodel_CXP9032245"
litp create -p /software/items/model_package/packages/autocellidmodel -t model-package -o name="ERICautocellidmodel_CXP9031283"








litp create -p /infrastructure/networking/routes/services_gateway_route -t route -o gateway="10.151.9.129" subnet="0.0.0.0/0"

litp create -p /infrastructure/storage/storage_profiles/ms_storage_profile -t storage-profile -o volume_driver="lvm"
litp create -p /infrastructure/storage/storage_profiles/ms_storage_profile/volume_groups/vg1 -t volume-group -o volume_group_name="vg_root"
litp create -p /infrastructure/storage/storage_profiles/ms_storage_profile/volume_groups/vg1/file_systems/fs_software -t file-system -o mount_point="/software" size="20G" snap_external="false" snap_size=1 type="ext4"
litp create -p /infrastructure/storage/storage_profiles/ms_storage_profile/volume_groups/vg1/file_systems/fs_data -t file-system -o mount_point="/var/lib/mysql" size="20G" snap_external="false" snap_size=50 type="ext4"
litp create -p /infrastructure/storage/storage_profiles/ms_storage_profile/volume_groups/vg1/physical_devices/pd1 -t physical-device -o device_name="ms_hd0"

litp create -p /infrastructure/systems/management_server -t system -o system_name="ieatlms3849-1"
litp create -p /infrastructure/systems/management_server/disks/disk0 -t disk -o bootable="true" disk_part="false" name="ms_hd0" size="100G" uuid="600508b1001ce13f72e5f8112edda7e1"


litp create -p /ms/configs/alias_configuration/aliases/ntp-server-2 -t alias -o alias_names="ntp-server2" address="10.140.2.9"
litp create -p /ms/configs/alias_configuration/aliases/ldap-1 -t alias -o alias_names="ldap-local" address="10.247.244.12"
litp create -p /ms/configs/alias_configuration/aliases/ldap-2 -t alias -o alias_names="ldap-remote" address="10.247.244.22"
litp create -p /ms/configs/alias_configuration/aliases/openidm -t alias -o alias_names="openidm-internal,openidm,idmhost-1,idmhost-2,idm-svc" address="10.247.246.12"
litp create -p /ms/configs/alias_configuration/aliases/idmdbhost -t alias -o alias_names="idmdbhost" address="10.247.244.7"
litp create -p /ms/configs/alias_configuration/aliases/sso-hostname -t alias -o alias_names="sso,sso-internal" address="10.247.246.56"
litp create -p /ms/configs/alias_configuration/aliases/hyperic-alias -t alias -o alias_names="monitoring-server" address="10.151.9.136"
litp create -p /ms/configs/alias_configuration/aliases/httpd-instance-1_alias -t alias -o alias_names="httpd-instance-1,iorfile1.ieatENM5183-1.athtem.eei.ericsson.se" address="10.247.246.10"
litp create -p /ms/configs/alias_configuration/aliases/httpd-instance-2_alias -t alias -o alias_names="httpd-instance-2,iorfile2.ieatENM5183-1.athtem.eei.ericsson.se" address="10.247.246.55"
litp create -p /ms/configs/alias_configuration/aliases/sso-instance-1_alias -t alias -o alias_names="sso-instance-1,sso-instance-1.ieatENM5183-1.athtem.eei.ericsson.se" address="10.247.246.89"
litp create -p /ms/configs/alias_configuration/aliases/sso-instance-2_alias -t alias -o alias_names="sso-instance-2,sso-instance-2.ieatENM5183-1.athtem.eei.ericsson.se" address="10.247.246.90"
litp create -p /ms/configs/alias_configuration/aliases/solr_alias -t alias -o alias_names="solr" address="10.247.246.47"
litp create -p /ms/configs/alias_configuration/aliases/emailservice_alias -t alias -o alias_names="emailservice" address="10.247.246.95"


litp create -p /ms/configs/alias_configuration/aliases/visinamingsb_alias -t alias -o alias_names="visinamingsb" address="10.247.246.58"
litp create -p /ms/configs/alias_configuration/aliases/visinamingsb-pub_alias -t alias -o alias_names="visinamingsb-pub" address="10.151.9.149"
litp create -p /ms/configs/alias_configuration/aliases/sentinelhost_alias -t alias -o alias_names="sentinelhost" address="10.140.2.9"
litp create -p /ms/configs/alias_configuration/aliases/db-1_alias -t alias -o alias_names="db-1" address="10.247.246.4"
litp create -p /ms/configs/alias_configuration/aliases/db-2_alias -t alias -o alias_names="db-2" address="10.247.246.5"
litp create -p /ms/configs/alias_configuration/aliases/svc-1_alias -t alias -o alias_names="svc-1" address="10.247.246.2"
litp create -p /ms/configs/alias_configuration/aliases/svc-2_alias -t alias -o alias_names="svc-2" address="10.247.246.3"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-httpd_alias -t alias -o alias_names="svc-1-httpd,httpd-1-internal" address="10.247.246.10"


litp create -p /ms/configs/alias_configuration/aliases/svc-2-httpd_alias -t alias -o alias_names="svc-2-httpd,httpd-2-internal" address="10.247.246.55"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-sso_alias -t alias -o alias_names="svc-1-sso,sso-1-internal" address="10.247.246.89"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-sso_alias -t alias -o alias_names="svc-2-sso,sso-2-internal" address="10.247.246.90"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-uiserv_alias -t alias -o alias_names="svc-1-uiserv,uiserv-1-internal" address="10.247.246.25"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-uiserv_alias -t alias -o alias_names="svc-2-uiserv,uiserv-2-internal" address="10.247.246.26"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-wpserv_alias -t alias -o alias_names="svc-1-wpserv,wpserv-1-internal" address="10.247.246.53"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-wpserv_alias -t alias -o alias_names="svc-2-wpserv,wpserv-2-internal" address="10.247.246.54"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-eventbasedclient_alias -t alias -o alias_names="svc-1-eventbasedclient,eventbasedclient-1-internal" address="10.247.246.17"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-eventbasedclient_alias -t alias -o alias_names="svc-2-eventbasedclient,eventbasedclient-2-internal" address="10.247.246.18"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-medrouter_alias -t alias -o alias_names="svc-1-medrouter,medrouter-1-internal,medrouter1-internal" address="10.247.246.13"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-medrouter_alias -t alias -o alias_names="svc-2-medrouter,medrouter-2-internal,medrouter2-internal" address="10.247.246.14"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-supervc_alias -t alias -o alias_names="svc-1-supervc,supervc-1-internal" address="10.247.246.15"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-supervc_alias -t alias -o alias_names="svc-2-supervc,supervc-2-internal" address="10.247.246.16"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-cmserv_alias -t alias -o alias_names="svc-1-cmserv,cmserv-1-internal,cmserv1-internal" address="10.247.246.21"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-mscm_alias -t alias -o alias_names="svc-1-mscm,mscm-1-internal,mscm1-internal" address="10.247.246.29"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-mscm_alias -t alias -o alias_names="svc-2-mscm,mscm-2-internal,mscm2-internal" address="10.247.246.30"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-mscmce_alias -t alias -o alias_names="svc-1-mscmce,mscmce-1-internal" address="10.247.246.87"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-mscmce_alias -t alias -o alias_names="svc-2-mscmce,mscmce-2-internal" address="10.247.246.88"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-comecimpolicy_alias -t alias -o alias_names="svc-1-comecimpolicy,comecimpolicy-1-internal" address="10.247.246.63"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-comecimpolicy_alias -t alias -o alias_names="svc-2-comecimpolicy,comecimpolicy-2-internal" address="10.247.246.64"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-cmrules_alias -t alias -o alias_names="svc-1-cmrules,cmrules-1-internal" address="10.247.246.103"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-cmrules_alias -t alias -o alias_names="svc-2-cmrules,cmrules-2-internal" address="10.247.246.104"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-netex_alias -t alias -o alias_names="svc-1-netex,netex-1-internal" address="10.247.246.23"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-netex_alias -t alias -o alias_names="svc-2-netex,netex-2-internal" address="10.247.246.24"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-secserv_alias -t alias -o alias_names="svc-1-secserv,secserv-1-internal,secserv1-internal" address="10.247.246.27"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-secserv_alias -t alias -o alias_names="svc-2-secserv,secserv-2-internal,secserv2-internal" address="10.247.246.28"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-sps_alias -t alias -o alias_names="svc-1-sps,sps-1-internal" address="10.247.246.65"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-sps_alias -t alias -o alias_names="svc-2-sps,sps-2-internal" address="10.247.246.66"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-pmserv_alias -t alias -o alias_names="svc-1-pmserv,pmserv-1-internal" address="10.247.246.19"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-pmserv_alias -t alias -o alias_names="svc-2-pmserv,pmserv-2-internal" address="10.247.246.20"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-mspm_alias -t alias -o alias_names="svc-1-mspm,mspm-1-internal,mspm1-internal" address="10.247.246.31"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-mspm_alias -t alias -o alias_names="svc-2-mspm,mspm-2-internal,mspm2-internal" address="10.247.246.32"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-fmalarmprocessing_alias -t alias -o alias_names="svc-1-fmalarmprocessing,fmalarmprocessing-1-internal" address="10.247.246.73"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-fmalarmprocessing_alias -t alias -o alias_names="svc-2-fmalarmprocessing,fmalarmprocessing-2-internal" address="10.247.246.74"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-fmhistory_alias -t alias -o alias_names="svc-1-fmhistory,fmhistory-1-internal" address="10.247.246.75"



litp create -p /ms/configs/alias_configuration/aliases/svc-2-fmhistory_alias -t alias -o alias_names="svc-2-fmhistory,fmhistory-2-internal" address="10.247.246.76"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-fmserv_alias -t alias -o alias_names="svc-1-fmserv,fmserv-1-internal" address="10.247.246.39"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-fmserv_alias -t alias -o alias_names="svc-2-fmserv,fmserv-2-internal" address="10.247.246.40"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-msfm_alias -t alias -o alias_names="svc-1-msfm,msfm-1-internal" address="10.247.246.37"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-msfm_alias -t alias -o alias_names="svc-2-msfm,msfm-2-internal" address="10.247.246.38"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-nbalarmirp_alias -t alias -o alias_names="svc-1-nbalarmirp,nbalarmirp-1-internal" address="10.247.246.41"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-nbalarmirp_alias -t alias -o alias_names="svc-2-nbalarmirp,nbalarmirp-2-internal" address="10.247.246.42"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-bnsiserv_alias -t alias -o alias_names="svc-1-bnsiserv,bnsiserv-1-internal" address="10.247.246.67"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-bnsiserv_alias -t alias -o alias_names="svc-2-bnsiserv,bnsiserv-2-internal" address="10.247.246.68"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-fmx_alias -t alias -o alias_names="svc-1-fmx,fmx-1-internal" address="10.247.246.85"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-fmx_alias -t alias -o alias_names="svc-2-fmx,fmx-2-internal" address="10.247.246.86"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-dlms_alias -t alias -o alias_names="svc-1-dlms,dlms-1-internal" address="10.247.246.105"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-dlms_alias -t alias -o alias_names="svc-2-dlms,dlms-2-internal" address="10.247.246.106"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-map-service_alias -t alias -o alias_names="svc-1-map-service,map-service-1-internal" address="10.247.246.77"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-map-service_alias -t alias -o alias_names="svc-2-map-service,map-service-2-internal" address="10.247.246.78"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-impexpserv_alias -t alias -o alias_names="svc-1-impexpserv,impexpserv-1-internal" address="10.247.246.43"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-impexpserv_alias -t alias -o alias_names="svc-2-impexpserv,impexpserv-2-internal" address="10.247.246.44"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-shmserv_alias -t alias -o alias_names="svc-1-shmserv,shmserv-1-internal" address="10.247.246.45"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-shmserv_alias -t alias -o alias_names="svc-2-shmserv,shmserv-2-internal" address="10.247.246.46"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-kpiserv_alias -t alias -o alias_names="svc-1-kpiserv,kpiserv-1-internal" address="10.247.246.51"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-kpiserv_alias -t alias -o alias_names="svc-2-kpiserv,kpiserv-2-internal" address="10.247.246.52"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-apserv_alias -t alias -o alias_names="svc-1-apserv,apserv-1-internal" address="10.247.246.59"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-apserv_alias -t alias -o alias_names="svc-2-apserv,apserv-2-internal" address="10.247.246.60"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-msap_alias -t alias -o alias_names="svc-1-msap,msap-1-internal" address="10.247.246.71"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-msap_alias -t alias -o alias_names="svc-2-msap,msap-2-internal" address="10.247.246.72"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-lcmserv_alias -t alias -o alias_names="svc-1-lcmserv,lcmserv-1-internal" address="10.247.246.61"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-lcmserv_alias -t alias -o alias_names="svc-2-lcmserv,lcmserv-2-internal" address="10.247.246.62"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-ipsmserv_alias -t alias -o alias_names="svc-1-ipsmserv,ipsmserv-1-internal" address="10.247.246.69"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-ipsmserv_alias -t alias -o alias_names="svc-2-ipsmserv,ipsmserv-2-internal" address="10.247.246.70"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-mscmip_alias -t alias -o alias_names="svc-1-mscmip,mscmip-1-internal" address="10.247.246.79"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-mscmip_alias -t alias -o alias_names="svc-2-mscmip,mscmip-2-internal" address="10.247.246.80"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-pkiraserv_alias -t alias -o alias_names="svc-1-pkiraserv,pkiraserv-1-internal" address="10.247.246.81"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-pkiraserv_alias -t alias -o alias_names="svc-2-pkiraserv,pkiraserv-2-internal" address="10.247.246.82"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-mssnmpfm_alias -t alias -o alias_names="svc-1-mssnmpfm,mssnmpfm-1-internal" address="10.247.246.93"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-mssnmpfm_alias -t alias -o alias_names="svc-2-mssnmpfm,mssnmpfm-2-internal" address="10.247.246.94"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-said_alias -t alias -o alias_names="svc-1-said,said-1-internal" address="10.247.246.91"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-said_alias -t alias -o alias_names="svc-2-said,said-2-internal" address="10.247.246.92"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-itservices_alias -t alias -o alias_names="svc-1-itservices,itservices-1-internal" address="10.247.246.96"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-itservices_alias -t alias -o alias_names="svc-2-itservices,itservices-2-internal" address="10.247.246.97"
litp create -p /ms/configs/alias_configuration/aliases/svc-1-dchistory_alias -t alias -o alias_names="svc-1-dchistory,dchistory-1-internal" address="10.247.246.101"
litp create -p /ms/configs/alias_configuration/aliases/svc-2-dchistory_alias -t alias -o alias_names="svc-2-dchistory,dchistory-2-internal" address="10.247.246.102"
litp create -p /ms/configs/alias_configuration/aliases/db1-service_alias -t alias -o alias_names="db1-service" address="10.247.244.17"
litp create -p /ms/configs/alias_configuration/aliases/ms-1_alias -t alias -o alias_names="ms-1" address="10.247.246.6"
litp create -p /ms/configs/alias_configuration/aliases/elasticsearch_alias -t alias -o alias_names="elasticsearch" address="10.247.244.31"
litp create -p /ms/configs/alias_configuration/aliases/mysql_alias -t alias -o alias_names="mysql" address="10.247.244.7"
litp create -p /ms/configs/alias_configuration/aliases/postgresql01_alias -t alias -o alias_names="postgresql01" address="10.247.244.2"
litp create -p /ms/configs/alias_configuration/aliases/jms01_alias -t alias -o alias_names="jms01" address="10.247.244.26"




litp create -p /ms/configs/group_configuration/groups/jboss -t group -o gid=205 groupname='jboss'
litp create -p /ms/configs/user_configuration/users/jboss_user -t user -o groupname='jboss' home='/home/jboss' name='jboss' shell='/bin/bash' uid=308

litp create -p /ms/configs/fw_config -t firewall-node-config -o drop_all='true'
litp create -p /ms/configs/fw_config/rules/fw_hyperic_server_in -t firewall-rule -o action=accept chain=INPUT dport="57004,57005" name="112 hyperic tcp agent to server ports" proto=tcp state=NEW

litp create -p /ms/configs/fw_config/rules/fw_hyperic_server_out -t firewall-rule -o action=accept chain=OUTPUT dport="57006" name="113 hyperic tcp server to agent port" proto=tcp state=NEW


litp create -p /ms/configs/fw_config/rules/fw_sfsudp -t firewall-rule -o action=accept dport="111,2049,4011,4001" name="011 sfsudp" proto=udp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_sfstcp -t firewall-rule -o action=accept dport="111,2049,4011,4001" name="012 sfstcp" proto=tcp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_vmmonitord -t firewall-rule -o action=accept dport="12987" name="018 vmmonitord" proto=tcp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_dns -t firewall-rule -o action=accept dport="53" name="021 DNS udp" proto=udp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_brs -t firewall-rule -o action=accept dport="1556,2821,4032,13724,13782" name="022 backuprestore tcp" proto=tcp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_ntp -t firewall-rule -o action=accept dport="123" name="029 NTP udp" proto=tcp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_dhcp_tcp -t firewall-rule -o action=accept dport="546,547,647,847" name="030 DHCP tcp" proto=tcp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_dhcp_udp -t firewall-rule -o action=accept dport="546,547,647,847" name="031 DHCP udp" proto=udp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_cobbler -t firewall-rule -o action=accept dport="25150,25151" name="032 cobbler" proto=udp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_cobbler_tcp -t firewall-rule -o action=accept dport="25150,25151" name="033 cobbler" proto=tcp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_nexus -t firewall-rule -o action=accept dport="8080,8443" name="034 nexus tcp" proto=tcp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_lserv -t firewall-rule -o action=accept dport="5093" name="035 lserv" proto=udp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_rpcbind -t firewall-rule -o action=accept dport="676" name="036 rpcbind" proto=udp state=NEW
litp create -p /ms/configs/fw_config/rules/fw_loop_back -t firewall-rule -o action=accept iniface=lo name="01 loop back" proto=all
litp create -p /ms/configs/fw_config/rules/fw_icmp -t firewall-rule -o action=accept name="100 icmp" proto=icmp
litp create -p /ms/configs/fw_config/rules/fw_http_allow_int -t firewall-rule -o action=accept provider="iptables" dport="80" name="101 allow http internal" proto=tcp state=NEW source="10.247.244.0/22"
litp create -p /ms/configs/fw_config/rules/fw_http_allow_stor -t firewall-rule -o action=accept dport="80" name="102 allow http storage" proto=tcp state=NEW provider="iptables" source="10.140.2.0/24"
litp create -p /ms/configs/fw_config/rules/fw_http_allow_serv -t firewall-rule -o action=accept dport="80" name="103 allow http services" proto=tcp state=NEW provider="iptables" source="10.151.9.128/26"
litp create -p /ms/configs/fw_config/rules/fw_http_allow_bkp -t firewall-rule -o action=accept dport="80" name="104 allow http backup" proto=tcp state=NEW provider="iptables" source="10.151.24.0/23"
litp create -p /ms/configs/fw_config/rules/fw_http_block -t firewall-rule -o action=accept dport="80" name="105 drop http" proto=tcp state=NEW provider="iptables"


litp inherit -p /ms/file_systems/nfsm-brsadm_home -s /infrastructure/storage/nfs_mounts/nfsm-brsadm_home
litp inherit -p /ms/file_systems/nfsm-storobs_home -s /infrastructure/storage/nfs_mounts/nfsm-storobs_home
litp inherit -p /ms/file_systems/nfsm-data -s /infrastructure/storage/nfs_mounts/nfsm-data
litp inherit -p /ms/file_systems/nfsm-ddc_data -s /infrastructure/storage/nfs_mounts/nfsm-ddc_data
litp inherit -p /ms/file_systems/nfsm-hcdumps -s /infrastructure/storage/nfs_mounts/nfsm-hcdumps
litp inherit -p /ms/file_systems/nfsm-mdt -s /infrastructure/storage/nfs_mounts/nfsm-mdt
litp inherit -p /ms/file_systems/nfsm-alex -s /infrastructure/storage/nfs_mounts/nfsm-alex

litp inherit -p /ms/items/common_repo -s /software/items/common_repo
litp inherit -p /ms/items/ms_repo -s /software/items/ms_repo
litp inherit -p /ms/items/model_repo -s /software/items/model_repo
litp inherit -p /ms/items/ntp_service -s /software/items/ntp_service
litp inherit -p /ms/items/ddc_package -s /software/items/ddc_package
litp inherit -p /ms/items/syslog8 -s /software/items/rsyslog8
litp inherit -p /ms/items/enm_configuration -s /software/items/enm_configuration
litp inherit -p /ms/items/config_manager -s /software/items/config_manager
litp inherit -p /ms/items/enm_utilities -s /software/items/enm_utilities
litp inherit -p /ms/items/enm_eniq_integration -s /software/items/enm_eniq_integration
litp inherit -p /ms/items/backup_restore_package -s /software/items/backup_restore_package
litp inherit -p /ms/items/backup_restore_ombs_package -s /software/items/backup_restore_ombs_package
litp inherit -p /ms/items/pibscripts -s /software/items/pibscripts
litp inherit -p /ms/items/model_package -s /software/items/model_package


litp create -p /ms/network_interfaces/eth0 -t eth -o bridge="br0" device_name="eth0" macaddress="D8:9D:67:32:E5:7C"
litp create -p /ms/network_interfaces/eth1 -t eth -o bridge="br1" device_name="eth1" macaddress="D8:9D:67:32:E5:7D"
litp create -p /ms/network_interfaces/eth2 -t eth -o bridge="br2" device_name="eth2" macaddress="D8:9D:67:32:E5:7E"
litp create -p /ms/network_interfaces/eth3 -t eth -o bridge="br3" device_name="eth3" macaddress="D8:9D:67:32:E5:7F"

litp create -p /ms/network_interfaces/br0 -t bridge -o ipaddress="10.151.9.136" network_name="services" device_name="br0"
litp create -p /ms/network_interfaces/br1 -t bridge -o ipaddress="10.140.2.9" network_name="storage" device_name="br1"
litp create -p /ms/network_interfaces/br2 -t bridge -o ipaddress="10.151.24.18" network_name="backup" device_name="br2"
litp create -p /ms/network_interfaces/br3 -t bridge -o ipaddress="10.247.246.6" network_name="internal" device_name="br3"


litp inherit -p /ms/routes/services_gateway_route -s /infrastructure/networking/routes/services_gateway_route 


litp create -p /ms/services/sentinel -t service -o cleanup_command="/sbin/service sentinel stop" service_name="sentinel"

litp create -p /ms/services/cobbler -t cobbler-service -o authentication="authn_configfile" ksm_ksname="litp.ks" ksm_path="/var/lib/cobbler/kickstarts" ksm_selinux_mode="enforcing" manage_dhcp="true" manage_dns="false" puppet_auto_setup="true"  remove_old_puppet_certs_automatically="true" rsync_disabled="false" sign_puppet_certs_automatically="true"

litp create -p /ms/services/hyperic_server -t hyperic-server -o cleanup_command="/bin/true" service_name="hyperics-server" mon_plugins_rpm_name="ERICenmmonitoring_CXP9031059" rpm_name="ERIChyperics_CXP9032070"
litp create -p /ms/services/hyperic_agent -t hyperic-agent -o cleanup_command="/bin/true" service_name="hyperics-agent" mon_api_rpm_name="ERIChypericc_CXP9032072" mon_tools_rpm_name="ERICmontools_CXP9031245" rpm_name="ERIChyperica_CXP9032071"


litp create -p /ms/services/mysqld -t mysql-server -o cleanup_command="/bin/true" service_name="mysqld" config_file="/etc/my.cnf" datadir="/var/lib/mysql" manage_config_file="true" package_name="mysql-server.x86_64" purge_conf_dir="false" restart="false" root_group="root"

litp create -p /ms/services/mysqld/override_options/opt1 -t mysql-override-option -o name="pid-file" section="mysqld" value="/var/run/mysqld/mysqld.pid"
litp create -p /ms/services/mysqld/override_options/opt2 -t mysql-override-option -o name="user" section="mysqld" value="mysql"


litp inherit -p /ms/storage_profile -s /infrastructure/storage/storage_profiles/ms_storage_profile
litp inherit -p /ms/system -s /infrastructure/systems/management_server


litp create_plan

