#!/usr/bin/expect -f

###Takes command line arguments:
#1 user to scp as
#2 password for scp connection
#3 ip to go to

set ip [lindex $argv 0];
set user [lindex $argv 1];
set pw [lindex $argv 2];
set local_path [lindex $argv 3];
set remote_path [lindex $argv 4];

set timeout 216000

# connect via scp
spawn scp -o StrictHostKeyChecking=no $local_path $user@$ip:$remote_path
#######################

expect "assword: "
send "$pw\r"
expect "]$ "
